In [2]:
%pip install pandas faker

Requirement already satisfied: pandas in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (3.0.1)
Collecting faker
  Downloading faker-40.11.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/grigo/gits/seminars/gfu/Python_individuell/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.11.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 36.9 MB/s  0:00:00
Installing collected packages: faker
Successfully installed faker-40.11.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
from faker import Faker
import random
import pandas as pd 
fake = Faker("de_DE")

In [4]:
def random_gender():
    return random.choice(["männlich", "weiblich", 'divers'])

def random_blood_type():
    return random.choice(["A+", "A-", "B+", "B-","O+", "O-","AB+","AB-"])

def random_smoker():
    return random.choice([True, False])

def random_allergies():
    return random.choice(["keine", "Pollen", "Nüsse", "Milch", "Gluten"])

def random_family_status():
    return random.choice(["ledig", "verheiratet", "geschieden", "verwitwet"])

In [5]:
patienten = []

for _ in range(50000):
    patient = {
    "PatientenID": fake.unique.uuid4(),
    "Versichertennummer": fake.bothify("??#######").upper(), # zwei Mal Buchstabe, 6 mal Zahl
    "Vorname": fake.first_name(),
    "Nachname": fake.last_name(),
    "Geburtsdatum": fake.date_of_birth(minimum_age=1, maximum_age=99),
    "Geschlecht": random_gender(),
    "Adresse": fake.address().replace('\n', ', '), # Bei Adresse die Neuzeilen durch Komma+Leerzeichen ersetzen
    "Telefon": fake.phone_number(),
    "Email": fake.unique.email(),
    "Blutgruppe": random_blood_type(),
    "Letzer_Besuch": fake.date_this_year(),
    "Hausarzt": f"{fake.first_name()} {fake.last_name()}",
    "Größe_cm":  random.randint(140, 220),
    "Gewicht_kg": random.randint(40, 130),
    "Raucher": random_smoker(),
    "Allergien": random_allergies(),
    "Letzes_EKG": fake.date_this_year(),
    "BMI": round(random.uniform(18,36),1), # Zufallszahl 
    "Familienstand": random_family_status(),
    "Beruf": fake.job(),
}
    patienten.append(patient)

patienten

[{'PatientenID': '08e6114e-942a-40e2-a297-7d5ff16eabc3',
  'Versichertennummer': 'ZX5587211',
  'Vorname': 'Ingetraud',
  'Nachname': 'Cichorius',
  'Geburtsdatum': datetime.date(1942, 5, 25),
  'Geschlecht': 'männlich',
  'Adresse': 'Trubinplatz 6, 02351 Hagenow',
  'Telefon': '(01243) 98095',
  'Email': 'ullmannanika@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 2, 4),
  'Hausarzt': 'Irmela Wulff',
  'Größe_cm': 152,
  'Gewicht_kg': 60,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 3, 8),
  'BMI': 33.0,
  'Familienstand': 'ledig',
  'Beruf': 'Designer'},
 {'PatientenID': '8312b64c-2723-4543-ad1b-d40c204e9067',
  'Versichertennummer': 'NH0739401',
  'Vorname': 'Camilla',
  'Nachname': 'Biggen',
  'Geburtsdatum': datetime.date(1976, 4, 29),
  'Geschlecht': 'männlich',
  'Adresse': 'Hoffmannstr. 1/7, 66392 Wittstock',
  'Telefon': '+49(0)9406 809692',
  'Email': 'ualbers@example.net',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2026, 1, 2),
  'Hausarzt': 'Nuri Tlustek',
  'Größe_cm': 184,
  'Gewicht_kg': 62,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2026, 1, 19),
  'BMI': 32.4,
  'Familienstand': 'verheiratet',
  'Beruf': 'Florist'},
 {'PatientenID': 'e7169510-cca4-4e7b-8e33-91136836b29d',
  'Versichertennummer': 'FY3580932',
  'Vorname': 'Hans-Günter',
  'Nachname': 'Koch II',
  'Geburtsdatum': datetime.date(1936, 10, 1),
  'Geschlecht': 'divers',
  'Adresse': 'Myriam-Dowerg-Ring 42-33, 80611 Oberviechtach',
  'Telefon': '0587472828',
  'Email': 'boucseinvirginia@example.org',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2026, 1, 20),
  'Hausarzt': 'Gundel Becker',
  'Größe_cm': 211,
  'Gewicht_kg': 44,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 2, 7),
  'BMI': 30.1,
  'Familienstand': 'verwitwet',
  'Beruf': 'Pilot'},
 {'PatientenID': '13f55c1d-5b4f-4bec-9821-5d4c7b690dfe',
  'Versichertennummer': 'AV5047810',
  'Vorname': 'Doris',
  'Nachname': 'Stadelmann',
  'Geburtsdatum': datetime.date(1988, 3, 31),
  'Geschlecht': 'männlich',
  'Adresse': 'Junkenstraße 21-45, 77040 Berlin',
  'Telefon': '05685 218013',
  'Email': 'hedydowerg@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2026, 1, 22),
  'Hausarzt': 'Mirco Noack',
  'Größe_cm': 150,
  'Gewicht_kg': 121,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 1, 9),
  'BMI': 26.9,
  'Familienstand': 'verwitwet',
  'Beruf': 'Bäcker'},
 {'PatientenID': 'a6c86b4f-ced9-4595-a604-bcc47b539d2a',
  'Versichertennummer': 'IR3445369',
  'Vorname': 'Luzia',
  'Nachname': 'Förster',
  'Geburtsdatum': datetime.date(1937, 8, 30),
  'Geschlecht': 'weiblich',
  'Adresse': 'Eigenwilligweg 7, 19317 Eggenfelden',
  'Telefon': '+49(0)7029 707823',
  'Email': 'tschentscherfaruk@example.net',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2026, 2, 23),
  'Hausarzt': 'Philip Stroh',
  'Größe_cm': 155,
  'Gewicht_kg': 96,
  'Raucher': True,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 3, 9),
  'BMI': 22.9,
  'Familienstand': 'geschieden',
  'Beruf': 'Medizininformatiker'},
 {'PatientenID': '7f6539e3-c706-40ea-a4f0-dc9e42e5d664',
  'Versichertennummer': 'BL2106322',
  'Vorname': 'Gloria',
  'Nachname': 'Mende',
  'Geburtsdatum': datetime.date(2008, 10, 2),
  'Geschlecht': 'weiblich',
  'Adresse': 'Kargegasse 43/31, 71624 Schmölln',
  'Telefon': '+49(0) 902937435',
  'Email': 'ritterfrancoise@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 3, 12),
  'Hausarzt': 'Silke Girschner',
  'Größe_cm': 198,
  'Gewicht_kg': 69,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 2, 21),
  'BMI': 18.4,
  'Familienstand': 'geschieden',
  'Beruf': 'Ausbaufacharbeiter'},
 {'PatientenID': '7cfd9942-4794-4393-acb4-d0521274742d',
  'Versichertennummer': 'CV2276619',
  'Vorname': 'Silva',
  'Nachname': 'Pechel',
  'Geburtsdatum': datetime.date(1985, 11, 26),
  'Geschlecht': 'divers',
  'Adresse': 'Bauerring 9699, 64668 Bruchsal',
  'Telefon': '+49 (0) 2793 527955',
  'Email': 'hermannleonore@example.org',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2026, 3, 15),
  'Hausarzt': 'Nadja Hofmann',
  'Größe_cm': 219,
  'Gewicht_kg': 58,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2026, 3, 18),
  'BMI': 31.2,
  'Familienstand': 'verwitwet',
  'Beruf': 'Mechaniker'},
 {'PatientenID': 'c382878f-81a0-4cb2-b7c6-e8b18db6f1b3',
  'Versichertennummer': 'KY1631919',
  'Vorname': 'Danilo',
  'Nachname': 'Becker',
  'Geburtsdatum': datetime.date(1996, 8, 22),
  'Geschlecht': 'männlich',
  'Adresse': 'Severin-Schinke-Platz 8/6, 61054 Olpe',
  'Telefon': '02056 525007',
  'Email': 'karl-augustkrebs@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 2, 2),
  'Hausarzt': 'Ismet Lübs',
  'Größe_cm': 155,
  'Gewicht_kg': 68,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 3, 13),
  'BMI': 19.4,
  'Familienstand': 'verheiratet',
  'Beruf': 'Elektroniker'},
 {'PatientenID': '88be034f-ac85-4542-aca5-8508e2986be3',
  'Versichertennummer': 'FS7829672',
  'Vorname': 'Helmar',
  'Nachname': 'Rohleder',
  'Geburtsdatum': datetime.date(2003, 8, 21),
  'Geschlecht': 'divers',
  'Adresse': 'Gertrude-Ullrich-Allee 1/4, 93741 Hannover',
  'Telefon': '(05334) 69255',
  'Email': 'gertzirmengard@example.com',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2026, 1, 9),
  'Hausarzt': 'Trudi Kade',
  'Größe_cm': 141,
  'Gewicht_kg': 128,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 2, 11),
  'BMI': 32.3,
  'Familienstand': 'verheiratet',
  'Beruf': 'Elektroniker'},
 {'PatientenID': '6f2f9a78-5bc8-4ffa-88b8-fc009c28d836',
  'Versichertennummer': 'BW1586472',
  'Vorname': 'Paulo',
  'Nachname': 'Ehlert',
  'Geburtsdatum': datetime.date(1997, 10, 24),
  'Geschlecht': 'männlich',
  'Adresse': 'Marta-Junk-Ring 98/53, 36713 Worbis',
  'Telefon': '+49(0)3816998159',
  'Email': 'marie-luise96@example.org',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 1, 13),
  'Hausarzt': 'Alban Flantz',
  'Größe_cm': 195,
  'Gewicht_kg': 120,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 2, 17),
  'BMI': 27.1,
  'Familienstand': 'verheiratet',
  'Beruf': 'Augenoptiker'},
 {'PatientenID': '5baf2944-5f49-4ee2-8736-0c838ebd1b73',
  'Versichertennummer': 'LK1697339',
  'Vorname': 'Drago',
  'Nachname': 'Rust',
  'Geburtsdatum': datetime.date(1941, 11, 18),
  'Geschlecht': 'männlich',
  'Adresse': 'Zobelring 3-8, 16069 Hoyerswerda',
  'Telefon': '(08753) 72674',
  'Email': 'tinomaelzer@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 3, 12),
  'Hausarzt': 'Aribert Buchholz',
  'Größe_cm': 183,
  'Gewicht_kg': 73,
  'Raucher': False,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2026, 2, 22),
  'BMI': 27.9,
  'Familienstand': 'ledig',
  'Beruf': 'Pilot'},
 {'PatientenID': 'bd77238b-6567-4917-8684-5e2863cdc8ab',
  'Versichertennummer': 'CL6798215',
  'Vorname': 'Jiri',
  'Nachname': 'Jessel',
  'Geburtsdatum': datetime.date(1937, 3, 19),
  'Geschlecht': 'männlich',
  'Adresse': 'Marie-Therese-Schmiedecke-Straße 0, 57164 Dachau',
  'Telefon': '+49(0)8343 52746',
  'Email': 'feliciakarz@example.net',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2026, 1, 4),
  'Hausarzt': 'Aysel Röhricht',
  'Größe_cm': 197,
  'Gewicht_kg': 74,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 2, 20),
  'BMI': 30.2,
  'Familienstand': 'verwitwet',
  'Beruf': 'Mathematiker'},
 {'PatientenID': '47f14489-74e2-4f47-babc-a13008dbbdbf',
  'Versichertennummer': 'UE2356193',
  'Vorname': 'Wilfriede',
  'Nachname': 'Hertrampf',
  'Geburtsdatum': datetime.date(1949, 9, 6),
  'Geschlecht': 'divers',
  'Adresse': 'Winklerstraße 341, 87639 Illertissen',
  'Telefon': '09929 70518',
  'Email': 'riehlreinhard@example.com',
  'Blutgruppe': 'B+',
  'Letzer_Besuch': datetime.date(2026, 1, 3),
  'Hausarzt': 'Ortwin Mitschke',
  'Größe_cm': 146,
  'Gewicht_kg': 127,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 2, 1),
  'BMI': 22.0,
  'Familienstand': 'geschieden',
  'Beruf': 'Krankenschwester'},
 {'PatientenID': '4778dea9-2e0d-44f7-83d6-d69d40d43445',
  'Versichertennummer': 'EL7640661',
  'Vorname': 'Karl-Wilhelm',
  'Nachname': 'Hendriks',
  'Geburtsdatum': datetime.date(1966, 8, 31),
  'Geschlecht': 'weiblich',
  'Adresse': 'Bruno-Stahr-Weg 28/30, 72641 Demmin',
  'Telefon': '+49(0)7171070103',
  'Email': 'neckbauer@example.com',
  'Blutgruppe': 'B-',
  'Letzer_Besuch': datetime.date(2026, 2, 24),
  'Hausarzt': 'Maria-Luise Wulff',
  'Größe_cm': 186,
  'Gewicht_kg': 49,
  'Raucher': True,
  'Allergien': 'keine',
  'Letzes_EKG': datetime.date(2026, 3, 6),
  'BMI': 20.9,
  'Familienstand': 'verwitwet',
  'Beruf': 'Mechaniker'},
 {'PatientenID': 'd2325e3e-7ae2-47fb-a9dc-571268e199e1',
  'Versichertennummer': 'DB2332636',
  'Vorname': 'Eileen',
  'Nachname': 'Scholz',
  'Geburtsdatum': datetime.date(1947, 10, 8),
  'Geschlecht': 'männlich',
  'Adresse': 'Hans-Hinrich-Bien-Gasse 56-14, 79953 Delitzsch',
  'Telefon': '0643048243',
  'Email': 'nikohermighausen@example.com',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2026, 1, 3),
  'Hausarzt': 'Gottlieb Heidrich',
  'Größe_cm': 217,
  'Gewicht_kg': 63,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 2, 26),
  'BMI': 18.1,
  'Familienstand': 'geschieden',
  'Beruf': 'Schornsteinfeger'},
 {'PatientenID': 'f5ed154e-2fd5-4318-baaa-82657445bbd0',
  'Versichertennummer': 'AO7335748',
  'Vorname': 'Carmine',
  'Nachname': 'Zimmer',
  'Geburtsdatum': datetime.date(2013, 9, 29),
  'Geschlecht': 'männlich',
  'Adresse': 'Miguel-Grein Groth-Straße 8/4, 10686 Berlin',
  'Telefon': '0091012652',
  'Email': 'schleichgerhart@example.net',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 3, 12),
  'Hausarzt': 'Lieschen Hornich',
  'Größe_cm': 197,
  'Gewicht_kg': 114,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 3, 15),
  'BMI': 29.9,
  'Familienstand': 'verwitwet',
  'Beruf': 'Programmierer'},
 {'PatientenID': 'ecbcf016-3e63-41b3-b138-15f015bc7c5f',
  'Versichertennummer': 'QB6289761',
  'Vorname': 'Ernst',
  'Nachname': 'Ritter',
  'Geburtsdatum': datetime.date(2007, 6, 28),
  'Geschlecht': 'divers',
  'Adresse': 'Heintzering 51/43, 31653 Borken',
  'Telefon': '0066937331',
  'Email': 'roskothsiegrun@example.net',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2026, 1, 19),
  'Hausarzt': 'Aldo Paffrath',
  'Größe_cm': 162,
  'Gewicht_kg': 47,
  'Raucher': True,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 3, 9),
  'BMI': 22.9,
  'Familienstand': 'verwitwet',
  'Beruf': 'Beamter'},
 {'PatientenID': '8877e9c1-2c97-41bd-88c1-a62f7461602c',
  'Versichertennummer': 'YF7837601',
  'Vorname': 'Melita',
  'Nachname': 'Kreusel',
  'Geburtsdatum': datetime.date(1989, 9, 28),
  'Geschlecht': 'divers',
  'Adresse': 'Gunpfplatz 2492, 70110 Wiedenbrück',
  'Telefon': '(02177) 024276',
  'Email': 'wheuser@example.org',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2026, 1, 10),
  'Hausarzt': 'Cynthia Jopich',
  'Größe_cm': 220,
  'Gewicht_kg': 129,
  'Raucher': False,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 1, 6),
  'BMI': 18.7,
  'Familienstand': 'geschieden',
  'Beruf': 'Schornsteinfeger'},
 {'PatientenID': '3b9db60b-f628-404d-9b89-064943c8e504',
  'Versichertennummer': 'BW2556479',
  'Vorname': 'Sergio',
  'Nachname': 'Jungfer',
  'Geburtsdatum': datetime.date(1940, 9, 1),
  'Geschlecht': 'divers',
  'Adresse': 'Köhlerstraße 30-64, 13101 Kelheim',
  'Telefon': '+49 (0) 7450 618153',
  'Email': 'fmargraf@example.net',
  'Blutgruppe': 'B+',
  'Letzer_Besuch': datetime.date(2026, 1, 25),
  'Hausarzt': 'Stefano Schönland',
  'Größe_cm': 171,
  'Gewicht_kg': 110,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 3, 20),
  'BMI': 31.0,
  'Familienstand': 'verwitwet',
  'Beruf': 'Fleischer'},
 {'PatientenID': '80faf7ba-7737-4a1f-b942-d59fd6a63358',
  'Versichertennummer': 'HV4875045',
  'Vorname': 'Dogan',
  'Nachname': 'Sorgatz',
  'Geburtsdatum': datetime.date(2003, 11, 4),
  'Geschlecht': 'männlich',
  'Adresse': 'Drubinweg 5/7, 99379 Altötting',
  'Telefon': '0105787897',
  'Email': 'leopold41@example.com',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2026, 1, 6),
  'Hausarzt': 'Antoinette Stroh',
  'Größe_cm': 199,
  'Gewicht_kg': 123,
  'Raucher': False,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 2, 22),
  'BMI': 19.5,
  'Familienstand': 'ledig',
  'Beruf': 'Chirurgiemechaniker'},
 {'PatientenID': 'bc9d74d8-3a69-42b7-9b05-2c0b214fee75',
  'Versichertennummer': 'KY2573527',
  'Vorname': 'Silvia',
  'Nachname': 'Geißler',
  'Geburtsdatum': datetime.date(1972, 2, 6),
  'Geschlecht': 'weiblich',
  'Adresse': 'Schwitalweg 6987, 37531 Heiligenstadt',
  'Telefon': '+49(0) 916941951',
  'Email': 'steffen75@example.com',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 2, 24),
  'Hausarzt': 'Hans-H. Baum',
  'Größe_cm': 193,
  'Gewicht_kg': 115,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 1, 31),
  'BMI': 18.8,
  'Familienstand': 'verheiratet',
  'Beruf': 'Medizininformatiker'},
 {'PatientenID': '12b73fc0-3c90-48f9-87b7-8d97df3d1df8',
  'Versichertennummer': 'VG6829493',
  'Vorname': 'Zeki',
  'Nachname': 'Keudel',
  'Geburtsdatum': datetime.date(2009, 9, 17),
  'Geschlecht': 'männlich',
  'Adresse': 'Eckhart-Trapp-Ring 945, 90230 Burgdorf',
  'Telefon': '+49 (0) 9159 101544',
  'Email': 'beerpetra@example.com',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2026, 2, 13),
  'Hausarzt': 'Immo Bohlander',
  'Größe_cm': 178,
  'Gewicht_kg': 103,
  'Raucher': True,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 3, 11),
  'BMI': 33.8,
  'Familienstand': 'verheiratet',
  'Beruf': 'Bäcker'},
 {'PatientenID': '1cc89f39-26c6-467f-8734-7d84e94db615',
  'Versichertennummer': 'ID7049363',
  'Vorname': 'Patrizia',
  'Nachname': 'Stadelmann',
  'Geburtsdatum': datetime.date(2003, 6, 1),
  'Geschlecht': 'weiblich',
  'Adresse': 'Nohlmansgasse 5-3, 99200 Parchim',
  'Telefon': '+49(0)2243 94680',
  'Email': 'jschwital@example.net',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2026, 2, 12),
  'Hausarzt': 'Zlatko Klapp',
  'Größe_cm': 173,
  'Gewicht_kg': 77,
  'Raucher': True,
  'Allergien': 'Milch',
  'Letzes_EKG': datetime.date(2026, 3, 14),
  'BMI': 22.5,
  'Familienstand': 'ledig',
  'Beruf': 'Augenoptiker'},
 {'PatientenID': 'e1846987-d7d8-4fd8-a87c-94c210008ebc',
  'Versichertennummer': 'MI8686956',
  'Vorname': 'Eveline',
  'Nachname': 'Kallert',
  'Geburtsdatum': datetime.date(2001, 5, 10),
  'Geschlecht': 'divers',
  'Adresse': 'Putzplatz 7-4, 55814 Steinfurt',
  'Telefon': '+49(0)1284 717777',
  'Email': 'rognerlidija@example.com',
  'Blutgruppe': 'AB+',
  'Letzer_Besuch': datetime.date(2026, 3, 18),
  'Hausarzt': 'Siegbert Pieper',
  'Größe_cm': 168,
  'Gewicht_kg': 73,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 1, 3),
  'BMI': 19.2,
  'Familienstand': 'verwitwet',
  'Beruf': 'Ausbaufacharbeiter'},
 {'PatientenID': '24b800b7-162e-49b3-930f-48695cfd4f01',
  'Versichertennummer': 'KC3590264',
  'Vorname': 'Peter-Michael',
  'Nachname': 'Dehmel',
  'Geburtsdatum': datetime.date(1933, 5, 27),
  'Geschlecht': 'männlich',
  'Adresse': 'Gusti-Hesse-Straße 612, 26006 Grimma',
  'Telefon': '03327 79264',
  'Email': 'gerditrommler@example.org',
  'Blutgruppe': 'A+',
  'Letzer_Besuch': datetime.date(2026, 3, 11),
  'Hausarzt': 'Knut Eckbauer',
  'Größe_cm': 210,
  'Gewicht_kg': 124,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 3, 5),
  'BMI': 22.8,
  'Familienstand': 'verheiratet',
  'Beruf': 'Ausbaufacharbeiter'},
 {'PatientenID': 'bd844bff-c165-4067-8cf0-c88bf6fb9f4b',
  'Versichertennummer': 'FD1911986',
  'Vorname': 'Irmtraut',
  'Nachname': 'Möchlichen',
  'Geburtsdatum': datetime.date(1988, 8, 8),
  'Geschlecht': 'weiblich',
  'Adresse': 'Fernando-Heinrich-Ring 183, 71824 Hainichen',
  'Telefon': '+49(0) 550216144',
  'Email': 'philomena50@example.net',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2026, 2, 24),
  'Hausarzt': 'Ludmilla Henck',
  'Größe_cm': 172,
  'Gewicht_kg': 44,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 2, 20),
  'BMI': 29.2,
  'Familienstand': 'ledig',
  'Beruf': 'Altenpfleger'},
 {'PatientenID': 'c82aedbd-4beb-4a67-a0b2-a8335c5fffc5',
  'Versichertennummer': 'BO5477122',
  'Vorname': 'Hartmuth',
  'Nachname': 'Hecker',
  'Geburtsdatum': datetime.date(1975, 5, 28),
  'Geschlecht': 'weiblich',
  'Adresse': 'Tintzmannplatz 9-5, 81664 Pegnitz',
  'Telefon': '(01497) 694026',
  'Email': 'cichoriusgunther@example.com',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2026, 2, 3),
  'Hausarzt': 'Lieselotte Gieß',
  'Größe_cm': 179,
  'Gewicht_kg': 83,
  'Raucher': False,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 2, 3),
  'BMI': 35.4,
  'Familienstand': 'ledig',
  'Beruf': 'Arzt'},
 {'PatientenID': '4d3f4b23-9eac-403e-a0d6-7cb7441d8532',
  'Versichertennummer': 'VA3674857',
  'Vorname': 'Roman',
  'Nachname': 'Seifert',
  'Geburtsdatum': datetime.date(1981, 12, 6),
  'Geschlecht': 'weiblich',
  'Adresse': 'Bertram-Knappe-Allee 83, 01837 Ahaus',
  'Telefon': '+49 (0) 4079 515192',
  'Email': 'biggenleonid@example.net',
  'Blutgruppe': 'A-',
  'Letzer_Besuch': datetime.date(2026, 3, 23),
  'Hausarzt': 'Sophie Meister',
  'Größe_cm': 148,
  'Gewicht_kg': 105,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 3, 18),
  'BMI': 22.8,
  'Familienstand': 'verwitwet',
  'Beruf': 'Designer'},
 {'PatientenID': '3ffb2580-c039-4c12-88bc-0f1120c46f9a',
  'Versichertennummer': 'RX2777719',
  'Vorname': 'Madeleine',
  'Nachname': 'Seidel',
  'Geburtsdatum': datetime.date(1954, 3, 30),
  'Geschlecht': 'divers',
  'Adresse': 'Anna-Lena-Scheel-Ring 7975, 01007 Gotha',
  'Telefon': '+49(0) 558371583',
  'Email': 'dimitriosstaude@example.org',
  'Blutgruppe': 'O+',
  'Letzer_Besuch': datetime.date(2026, 3, 4),
  'Hausarzt': 'Engin Grein Groth',
  'Größe_cm': 143,
  'Gewicht_kg': 116,
  'Raucher': True,
  'Allergien': 'Gluten',
  'Letzes_EKG': datetime.date(2026, 1, 5),
  'BMI': 35.2,
  'Familienstand': 'verheiratet',
  'Beruf': 'Winzer'},
 {'PatientenID': '158a2b31-d9dd-4c50-ac54-198c982ef12e',
  'Versichertennummer': 'XA5658956',
  'Vorname': 'Hans-Jochen',
  'Nachname': 'Röhrdanz',
  'Geburtsdatum': datetime.date(1991, 2, 18),
  'Geschlecht': 'männlich',
  'Adresse': 'Schülerallee 8/2, 48491 Bernburg',
  'Telefon': '+49(0)9019 48830',
  'Email': 'mohammedbeier@example.org',
  'Blutgruppe': 'AB-',
  'Letzer_Besuch': datetime.date(2026, 2, 28),
  'Hausarzt': 'Klaus-Ulrich Schmiedt',
  'Größe_cm': 152,
  'Gewicht_kg': 87,
  'Raucher': True,
  'Allergien': 'Nüsse',
  'Letzes_EKG': datetime.date(2026, 2, 17),
  'BMI': 34.9,
  'Familienstand': 'geschieden',
  'Beruf': 'Designer'},
 {'PatientenID': '652526cb-3bdc-4532-b2ff-2638bf7993ed',
  'Versichertennummer': 'US9494682',
  'Vorname': 'Berend',
  'Nachname': 'Thanel',
  'Geburtsdatum': datetime.date(2021, 7, 9),
  'Geschlecht': 'weiblich',
  'Adresse': 'Peukertgasse 57, 28714 Miltenberg',
  'Telefon': '08478 34374',
  'Email': 'nschuchhardt@example.org',
  'Blutgruppe': 'O-',
  'Letzer_Besuch': datetime.date(2026, 2, 27),
  'Hausarzt': 'Ramon Stiebitz',
  'Größe_cm': 158,
  'Gewicht_kg': 54,
  'Raucher': False,
  'Allergien': 'Pollen',
  'Letzes_EKG': datetime.date(2026, 2, 19),
  'BMI': 23.8,
  'Familienstand': 'verheiratet',
  'Beruf': 'Informatiker'},
 {'PatientenID': '600e1a77-4c0c-4de1-9594-962a9f593b86',
  'Versichertennummer': 'UD1637367',

In [6]:
df = pd.DataFrame(patienten)
df

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,08e6114e-942a-40e2-a297-7d5ff16eabc3,ZX5587211,Ingetraud,Cichorius,1942-05-25,männlich,"Trubinplatz 6, 02351 Hagenow",(01243) 98095,ullmannanika@example.net,AB-,2026-02-04,Irmela Wulff,152,60,False,Nüsse,2026-03-08,33.0,ledig,Designer
1,8312b64c-2723-4543-ad1b-d40c204e9067,NH0739401,Camilla,Biggen,1976-04-29,männlich,"Hoffmannstr. 1/7, 66392 Wittstock",+49(0)9406 809692,ualbers@example.net,O-,2026-01-02,Nuri Tlustek,184,62,True,keine,2026-01-19,32.4,verheiratet,Florist
2,e7169510-cca4-4e7b-8e33-91136836b29d,FY3580932,Hans-Günter,Koch II,1936-10-01,divers,"Myriam-Dowerg-Ring 42-33, 80611 Oberviechtach",0587472828,boucseinvirginia@example.org,O+,2026-01-20,Gundel Becker,211,44,True,Nüsse,2026-02-07,30.1,verwitwet,Pilot
3,13f55c1d-5b4f-4bec-9821-5d4c7b690dfe,AV5047810,Doris,Stadelmann,1988-03-31,männlich,"Junkenstraße 21-45, 77040 Berlin",05685 218013,hedydowerg@example.com,A+,2026-01-22,Mirco Noack,150,121,False,Milch,2026-01-09,26.9,verwitwet,Bäcker
4,a6c86b4f-ced9-4595-a604-bcc47b539d2a,IR3445369,Luzia,Förster,1937-08-30,weiblich,"Eigenwilligweg 7, 19317 Eggenfelden",+49(0)7029 707823,tschentscherfaruk@example.net,A-,2026-02-23,Philip Stroh,155,96,True,Milch,2026-03-09,22.9,geschieden,Medizininformatiker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,a8bbab12-60c3-4f59-830c-52319c10627f,YM2243450,Luisa,Fiebig,2021-09-01,weiblich,"Trappstr. 4266, 59406 Main-Höchst",01324 540942,wriehl@example.org,B+,2026-01-13,Daniel Heuser,206,80,True,Pollen,2026-03-06,34.2,verheiratet,Chemikant
49996,b83488a0-9c40-4643-abf4-ae871c956ba2,DT3403272,Magdalene,Harloff,1997-03-22,weiblich,"Wolfram-Lindau-Weg 0, 69352 Fürstenwalde",08638082651,wweinhold@example.org,O+,2026-01-30,Pierre Faust,175,111,True,Gluten,2026-03-08,28.3,ledig,Mechaniker
49997,7a7e094e-5f76-4a9d-8e4a-781baee94aa1,HK6273506,Luka,Ernst,1965-02-20,divers,"Traugott-Dussen van-Gasse 9, 77436 Angermünde",+49(0)0789 493987,walter55@example.org,AB-,2026-02-25,Ulrike Anders,145,40,False,Pollen,2026-02-21,35.0,verheiratet,Beamter
49998,b2711192-3f70-4eef-ab36-88bddb527614,JG6868501,Olivia,Drewes,1936-04-17,weiblich,"Gröttnergasse 2-8, 13199 Rehau",06218584158,dariusz38@example.net,A+,2026-02-28,Slawomir Berger,182,44,False,Nüsse,2026-03-02,31.1,ledig,Informatiker
49999,668e01f5-12b7-4a50-a7d0-2db4a176cb1b,VL5028303,Karl-Georg,Tröst,2005-08-17,divers,"Grafplatz 5/3, 76835 Saarlouis",+49(0)3679 39954,stiffelhans-dieter@example.com,O+,2026-03-09,Sieglinde Beckmann,201,120,True,Nüsse,2026-01-06,32.7,verwitwet,Arzt

In [9]:
df.head() # die ersten 10 Eintragungen

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,08e6114e-942a-40e2-a297-7d5ff16eabc3,ZX5587211,Ingetraud,Cichorius,1942-05-25,männlich,"Trubinplatz 6, 02351 Hagenow",(01243) 98095,ullmannanika@example.net,AB-,2026-02-04,Irmela Wulff,152,60,False,Nüsse,2026-03-08,33.0,ledig,Designer
1,8312b64c-2723-4543-ad1b-d40c204e9067,NH0739401,Camilla,Biggen,1976-04-29,männlich,"Hoffmannstr. 1/7, 66392 Wittstock",+49(0)9406 809692,ualbers@example.net,O-,2026-01-02,Nuri Tlustek,184,62,True,keine,2026-01-19,32.4,verheiratet,Florist
2,e7169510-cca4-4e7b-8e33-91136836b29d,FY3580932,Hans-Günter,Koch II,1936-10-01,divers,"Myriam-Dowerg-Ring 42-33, 80611 Oberviechtach",0587472828,boucseinvirginia@example.org,O+,2026-01-20,Gundel Becker,211,44,True,Nüsse,2026-02-07,30.1,verwitwet,Pilot
3,13f55c1d-5b4f-4bec-9821-5d4c7b690dfe,AV5047810,Doris,Stadelmann,1988-03-31,männlich,"Junkenstraße 21-45, 77040 Berlin",05685 218013,hedydowerg@example.com,A+,2026-01-22,Mirco Noack,150,121,False,Milch,2026-01-09,26.9,verwitwet,Bäcker
4,a6c86b4f-ced9-4595-a604-bcc47b539d2a,IR3445369,Luzia,Förster,1937-08-30,weiblich,"Eigenwilligweg 7, 19317 Eggenfelden",+49(0)7029 707823,tschentscherfaruk@example.net,A-,2026-02-23,Philip Stroh,155,96,True,Milch,2026-03-09,22.9,geschieden,Medizininformatiker

In [8]:
df.tail(10) # die letzten 10 Eintragungen

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
49990,55eef0e7-eccd-4d52-bc24-9c4c14a08612,MC4020968,Stefan,Schmidt,2016-07-22,männlich,"Evamaria-Hendriks-Gasse 7-9, 01627 Weißwasser",+49(0) 609360114,juliebeyer@example.net,A+,2026-02-13,Betti Girschner,170,59,True,Gluten,2026-03-08,28.4,verwitwet,Bäcker
49991,e7981013-f9f4-4d17-9abf-9b1774c1e1db,VX6150897,Elfriede,Junck,1973-07-04,divers,"Thiesstr. 17/92, 30205 Kelheim",00652 97249,btschentscher@example.com,A-,2026-03-09,Hans-J. Lindau,164,62,False,Gluten,2026-02-11,27.5,ledig,Chemikant
49992,ac89082f-5304-4443-87da-c58ba8b8e6dc,YK5060384,Ludwina,Ruppert,1946-10-14,weiblich,"Sigfried-Scholz-Gasse 66-97, 86207 Wesel",01019 39196,beatawagenknecht@example.com,AB-,2026-02-07,Leonhard Eigenwillig,204,105,False,Nüsse,2026-03-11,25.5,ledig,Friseur
49993,60d14aa3-ab10-4c8a-a84f-c12aaf416a60,MV5205665,Cornelia,Rose,1932-10-21,männlich,"Bolanderstr. 32-23, 93627 Merseburg",+49(0) 190639396,usoelzer@example.net,A-,2026-01-24,Tania Adolph,202,91,True,Milch,2026-03-02,33.0,verheiratet,Augenoptiker
49994,fbf62220-3d7b-46c5-ab74-9a5339d9626b,GE7939120,Helmar,Walter,1973-12-13,weiblich,"Milica-Kitzmann-Straße 2/8, 93069 Ahaus",05601 68835,erdogangnatz@example.com,AB+,2026-01-16,Gabor Haering,150,99,False,Gluten,2026-02-10,22.2,verheiratet,Binnenschiffer
49995,a8bbab12-60c3-4f59-830c-52319c10627f,YM2243450,Luisa,Fiebig,2021-09-01,weiblich,"Trappstr. 4266, 59406 Main-Höchst",01324 540942,wriehl@example.org,B+,2026-01-13,Daniel Heuser,206,80,True,Pollen,2026-03-06,34.2,verheiratet,Chemikant
49996,b83488a0-9c40-4643-abf4-ae871c956ba2,DT3403272,Magdalene,Harloff,1997-03-22,weiblich,"Wolfram-Lindau-Weg 0, 69352 Fürstenwalde",08638082651,wweinhold@example.org,O+,2026-01-30,Pierre Faust,175,111,True,Gluten,2026-03-08,28.3,ledig,Mechaniker
49997,7a7e094e-5f76-4a9d-8e4a-781baee94aa1,HK6273506,Luka,Ernst,1965-02-20,divers,"Traugott-Dussen van-Gasse 9, 77436 Angermünde",+49(0)0789 493987,walter55@example.org,AB-,2026-02-25,Ulrike Anders,145,40,False,Pollen,2026-02-21,35.0,verheiratet,Beamter
49998,b2711192-3f70-4eef-ab36-88bddb527614,JG6868501,Olivia,Drewes,1936-04-17,weiblich,"Gröttnergasse 2-8, 13199 Rehau",06218584158,dariusz38@example.net,A+,2026-02-28,Slawomir Berger,182,44,False,Nüsse,2026-03-02,31.1,ledig,Informatiker
49999,668e01f5-12b7-4a50-a7d0-2db4a176cb1b,VL5028303,Karl-Georg,Tröst,2005-08-17,divers,"Grafplatz 5/3, 76835 Saarlouis",+49(0)3679 39954,stiffelhans-dieter@example.com,O+,2026-03-09,Sieglinde Beckmann,201,120,True,Nüsse,2026-01-06,32.7,verwitwet,Arzt

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PatientenID         50000 non-null  object
 1   Versichertennummer  50000 non-null  object
 2   Vorname             50000 non-null  object
 3   Nachname            50000 non-null  object
 4   Geburtsdatum        50000 non-null  object
 5   Geschlecht          50000 non-null  object
 6   Adresse             50000 non-null  object
 7   Telefon             50000 non-null  object
 8   Email               50000 non-null  object
 9   Blutgruppe          50000 non-null  object
 10  Letzer_Besuch       50000 non-null  object
 11  Hausarzt            50000 non-null  object
 12  Größe_cm            50000 non-null  int64
 13  Gewicht_kg          50000 non-null  int64
 14  Raucher             50000 non-null  bool
 15  Allergien           50000 non-null  object
 16  Letzes_EKG          50000 non-null  object
 17  BMI                 50000 non-null  float64
 18  Familienstand       50000 non-null  object
 19  Beruf               50000 non-null  object
dtypes: bool(1), float64(1), int64(2), object(16)
memory usage: 7.3+ MB

In [9]:
df.BMI

0        28.4
1        30.4
2        26.5
3        30.6
4        32.7
         ...
49995    21.9
49996    28.8
49997    33.9
49998    21.1
49999    25.0
Name: BMI, Length: 50000, dtype: float64

In [10]:
df[["Vorname","Nachname","Geburtsdatum"]] # Zugriff auf mehrere Spalten

           Vorname    Nachname Geburtsdatum
0        Ingetraud   Cichorius   1942-05-25
1          Camilla      Biggen   1976-04-29
2      Hans-Günter     Koch II   1936-10-01
3            Doris  Stadelmann   1988-03-31
4            Luzia     Förster   1937-08-30
...            ...         ...          ...
49995        Luisa      Fiebig   2021-09-01
49996    Magdalene     Harloff   1997-03-22
49997         Luka       Ernst   1965-02-20
49998       Olivia      Drewes   1936-04-17
49999   Karl-Georg       Tröst   2005-08-17

[50000 rows x 3 columns]

In [11]:
n_df = df[["Vorname","Nachname","Geburtsdatum"]].copy() # tiefe Kopie
n_df["Alter"] = pd.Timestamp("now").year - pd.to_datetime(n_df["Geburtsdatum"]).dt.year
n_df["Geschlecht"] = df["Geschlecht"]
n_df["Raucher"] = df["Raucher"]
# Frauen zwischen 18 und 30, Nichtraucherin
n_df[(n_df["Alter"] >= 18) & (n_df["Alter"] < 30) & (n_df["Geschlecht"] == "weiblich") & (~ n_df["Raucher"])].head()

    Vorname   Nachname Geburtsdatum  Alter Geschlecht  Raucher
61   Jasmin  Cichorius   2005-03-11     21   weiblich    False
105  Louise     Etzold   2006-09-24     20   weiblich    False
126   Sedat      Beier   2005-02-11     21   weiblich    False
152    Gert   Weihmann   2001-03-09     25   weiblich    False
309   Cindy     Franke   2008-05-31     18   weiblich    False

In [12]:
n_df["BMI"] = df["BMI"]

def bmi_class(bmi):
    if bmi < 18.5:
        return "Untergewicht"
    elif bmi < 25:
        return "Normalgewicht"
    elif bmi < 30:
        return "Übergewicht"
    else:
        return "Adipositas"

n_df["BMI_Klasse"] = n_df["BMI"].apply(lambda bmi: bmi_class(bmi))

# Aufgabe: 
# Berechnen Sie die Altersgruppen als neue Spalte in n_df
# "Kind" (unter 18), "Erwachsen", "Senior" (ab 65)

def altersgruppe(alter):
    if alter<18:
        return "Kind"
    elif alter < 65:
        return "Erwachsen"
    else:
        return "Senior"

n_df["Altersgruppe"] = n_df["Alter"].apply(lambda alter: altersgruppe(alter))
n_df

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe
0,Svetlana,Scholz,1975-03-11,50,weiblich,True,28.4,Übergewicht,Erwachsen
1,Linda,Ackermann,1978-03-17,47,divers,False,30.4,Adipositas,Erwachsen
2,Karoline,Jüttner,1937-09-27,88,weiblich,True,26.5,Übergewicht,Senior
3,Andrew,Kobelt,1960-09-23,65,weiblich,False,30.6,Adipositas,Senior
4,James,Stiffel,1951-06-21,74,divers,False,32.7,Adipositas,Senior
...,...,...,...,...,...,...,...,...,...
49995,Ivana,Thies,2016-05-13,9,divers,True,21.9,Normalgewicht,Kind
49996,Anke,Budig,1935-12-27,90,männlich,True,28.8,Übergewicht,Senior
49997,Moritz,Rogge,1930-04-07,95,weiblich,True,33.9,Adipositas,Senior
49998,Stephanie,Müller,1974-09-23,51,weiblich,False,21.1,Normalgewicht,Erwachsen
49999,Hajo,Gierschner,2013-06-25,12,männlich,True,25.0,Übergewicht,Kind

In [13]:
def filter_normalgewicht(df):
    return df[df["BMI_Klasse"] == "Normalgewicht"]

def filter_altersgruppe(df,altersgruppe):
    return df[df["Altersgruppe"] == altersgruppe]



def blutgruppe_part(df,col):
    df["Blutgruppe"] = col
    return df[(df["Blutgruppe"]=="0+") | (df["Blutgruppe"] == "AB+")]



df_normalgewicht = (n_df
    .pipe(filter_normalgewicht)
    .sort_values("Alter", ascending =False)
)
# Data Transformation Pipeline
df_normerwachsen = (n_df
    .pipe(filter_normalgewicht)
    .pipe(filter_altersgruppe, "Erwachsen")
    .sort_values("Alter", ascending =False)
)
df_normerwachsen

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe
14187,Wilfriede,Paffrath,1961-12-20,64,weiblich,True,20.3,Normalgewicht,Erwachsen
49613,Regine,Köster,1961-12-20,64,divers,True,18.8,Normalgewicht,Erwachsen
49597,Yvette,Hoffmann,1961-01-12,64,weiblich,False,18.8,Normalgewicht,Erwachsen
10852,Jozef,Tröst,1961-11-30,64,weiblich,True,22.8,Normalgewicht,Erwachsen
6149,Korbinian,Jungfer,1961-05-25,64,männlich,False,21.7,Normalgewicht,Erwachsen
...,...,...,...,...,...,...,...,...,...
20333,Micha,Naser,2007-02-12,18,weiblich,True,20.5,Normalgewicht,Erwachsen
20285,Rudi,Gunpf,2007-03-02,18,divers,False,23.5,Normalgewicht,Erwachsen
20237,Johanna,Zimmer,2007-04-07,18,divers,True,20.5,Normalgewicht,Erwachsen
19880,Frederike,Bender,2007-09-30,18,divers,True,21.9,Normalgewicht,Erwachsen
13,Kazim,Rogge,2007-11-21,18,männlich,True,23.9,Normalgewicht,Erwachsen

In [14]:
# Aufgabe: 
# Schreiben Sie eine Pipeline, welche eine Spalte Blutgruppe zum df hinzufügt, nach Blutgruppe 0+ oder AB+ filtert und nur Kinder anzeigt.
# Wenden Sie die Pipeline auf n_df an.   

df_ = (n_df
    .pipe(blutgruppe_part,df["Blutgruppe"])
    .pipe(filter_altersgruppe, "Kind")
)

df_

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe,Blutgruppe
12,Käthe,Dietz,2015-03-21,10,männlich,True,32.5,Adipositas,Kind,AB+
75,Axel,Linke,2010-11-03,15,weiblich,False,27.0,Übergewicht,Kind,AB+
159,Silvester,Girschner,2011-04-07,14,weiblich,True,26.2,Übergewicht,Kind,AB+
164,Ahmad,Klapp,2021-07-05,4,divers,False,35.7,Adipositas,Kind,AB+
209,Gülsen,Haering,2018-11-12,7,weiblich,False,34.3,Adipositas,Kind,AB+
...,...,...,...,...,...,...,...,...,...,...
49785,Cora,Reinhardt,2024-04-30,1,weiblich,True,29.8,Übergewicht,Kind,AB+
49796,Cord,Hoffmann,2014-10-15,11,divers,True,21.8,Normalgewicht,Kind,AB+
49832,Hendrik,Krein,2018-10-11,7,männlich,False,19.3,Normalgewicht,Kind,AB+
49852,Anett,Pechel,2015-11-29,10,divers,False,32.7,Adipositas,Kind,AB+
49877,Carmine,Kallert,2017-10-14,8,weiblich,True,20.8,Normalgewicht,Kind,AB+

In [15]:
# Query - SQL-ähnliches Filtern
# Männer, BMI>30

n_df.query("Geschlecht == 'männlich' and BMI > 30")

,Vorname,Nachname,Geburtsdatum,Alter,Geschlecht,Raucher,BMI,BMI_Klasse,Altersgruppe,Blutgruppe
12,Käthe,Dietz,2015-03-21,10,männlich,True,32.5,Adipositas,Kind,AB+
32,Karl-Josef,Bauer,1995-09-20,30,männlich,True,33.5,Adipositas,Erwachsen,A+
46,Ingrid,Beer,1953-07-08,72,männlich,True,32.9,Adipositas,Senior,O+
54,Wojciech,Margraf,1934-09-02,91,männlich,True,34.3,Adipositas,Senior,A+
65,Hans-Michael,Gnatz,1927-12-20,98,männlich,False,34.3,Adipositas,Senior,B-
...,...,...,...,...,...,...,...,...,...,...
49945,Undine,Kallert,1984-12-21,41,männlich,False,33.7,Adipositas,Erwachsen,B+
49958,Nadeshda,Heuser,2007-05-20,18,männlich,False,30.5,Adipositas,Erwachsen,B+
49960,Marliese,Wagenknecht,1998-10-28,27,männlich,False,33.4,Adipositas,Erwachsen,O+
49969,Jaroslaw,Otto,1980-04-20,45,männlich,False,33.3,Adipositas,Erwachsen,B-
49975,Traute,Lindau,1987-04-01,38,männlich,True,34.4,Adipositas,Erwachsen,A-

In [24]:
df

,PatientenID,Versichertennummer,Vorname,Nachname,Geburtsdatum,Geschlecht,Adresse,Telefon,Email,Blutgruppe,Letzer_Besuch,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand,Beruf
0,b24ff43e-a903-4789-b2f6-4056773e3a06,AQ2755005,Svetlana,Scholz,1975-03-11,weiblich,"Fechnerring 6-5, 88532 Erding",07311 236676,heckertabea@example.net,A-,2025-03-01,Cäcilie Kabus,149,74,True,Nüsse,2025-05-29,28.4,geschieden,Techniker
1,fbffa844-ec1d-4f20-9a0b-5474dfcaf702,XB8073653,Linda,Ackermann,1978-03-17,divers,"Wähnerweg 7/5, 57649 Euskirchen",+49(0)6282711059,kargerene@example.org,AB+,2025-04-28,Konstanze Binner,190,63,False,Pollen,2025-04-20,30.4,ledig,Friseur
2,65d26661-3f6a-4d52-847d-d722d7d0cc25,XC1598876,Karoline,Jüttner,1937-09-27,weiblich,"Frida-Höfig-Ring 41/17, 37134 Dachau",+49(0)7142 95095,joachimjunitz@example.net,A+,2025-03-11,Constance Hermighausen,169,68,True,Pollen,2025-07-10,26.5,geschieden,Bäcker
3,def9fe72-2ba0-44d8-bbf5-fe9c8df803a1,HP3422006,Andrew,Kobelt,1960-09-23,weiblich,"Ole-Schmiedt-Straße 38, 42082 Hechingen",06705 142476,wilhelminelehmann@example.com,B-,2025-03-24,Erdogan Sauer,145,87,False,Milch,2025-07-25,30.6,verwitwet,Beamter
4,da1bc0e2-73bd-4ccb-abb5-0b6b180266a1,SP6375505,James,Stiffel,1951-06-21,divers,"Wolfgang-Förster-Gasse 65/17, 16662 Roth",+49(0)1601 00257,ulrike39@example.org,AB-,2025-07-28,Marie-Therese Wiek,175,123,False,Milch,2025-03-10,32.7,ledig,Chirurgiemechaniker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0a3b1093-4663-4120-8bc2-1197ce154368,GZ1982764,Ivana,Thies,2016-05-13,divers,"Juliane-Drub-Weg 4552, 79928 Rothenburg ob der...",00210357569,weitzelreinhild@example.com,AB-,2025-03-04,Selma Pieper,206,115,True,Nüsse,2025-04-15,21.9,verwitwet,Schornsteinfeger
49996,08fa3657-bdd6-43ba-b60b-d700f670d008,XI4160721,Anke,Budig,1935-12-27,männlich,"Bolzmannallee 7-1, 50877 Borna",03151 77049,marie-louise75@example.org,AB-,2025-05-13,Erdogan Lorch,184,77,True,Nüsse,2025-02-24,28.8,verwitwet,Techniker
49997,2642b74a-a90e-4b84-8129-be66d9bcdc42,BL2954542,Moritz,Rogge,1930-04-07,weiblich,"Hans Josef-Kostolzin-Ring 98/78, 98384 Ludwigs...",(07597) 79576,theo39@example.org,AB+,2025-04-28,Nikolas Seidel,164,113,True,Gluten,2025-03-24,33.9,geschieden,Techniker
49998,907cc2ce-8c66-4e7a-87c1-5149879b67ab,TX5400491,Stephanie,Müller,1974-09-23,weiblich,"Atzlerstraße 3-1, 23288 Regensburg",00078 011735,erwinsoeding@example.com,B+,2025-01-07,Mehdi Niemeier,146,91,False,Gluten,2025-03-10,21.1,geschieden,Friseur
49999,662acc24-641b-4c63-91da-63613720c9fd,RX2993627,Hajo,Gierschner,2013-06-25,männlich,"Kristine-Pölitz-Weg 4-3, 89851 Wittenberg",+49(0)0636971893,sinaweinhage@example.net,A-,2025-07-21,Jens-Peter Koch II,185,124,True,Nüsse,2025-01-29,25.0,verwitwet,Artist

In [40]:
# Gruppenweise Mittelwerte

agg_df = df.groupby(["Geschlecht", "Raucher"])[["Größe_cm", "Gewicht_kg", "BMI" ]].agg(
    [
        'mean', 
        'std',  # Standartabweichung
        'min', 
        'max',
    ]
) 

agg_df["Gewicht_kg"]["std"]

Geschlecht  Raucher
divers      False      26.326542
            True       26.153594
männlich    False      26.232996
            True       26.329325
weiblich    False      26.254280
            True       26.271550
Name: std, dtype: float64

In [42]:
df.groupby(["Geschlecht", "Raucher"])[["Größe_cm", "Gewicht_kg", "BMI" ]].agg(
    {
        "Größe_cm": "mean",
        "Gewicht_kg": "mean",
        "BMI": "max",
    }
)

                      Größe_cm  Gewicht_kg   BMI
Geschlecht Raucher
divers     False    179.357433   85.124044  36.0
           True     180.352687   85.193618  36.0
männlich   False    179.794984   85.073481  36.0
           True     179.808477   85.357056  36.0
weiblich   False    180.435711   85.554343  36.0
           True     179.723637   84.833413  36.0

In [ ]:
# Aufgabe: 
# 1. Erstellen Sie eine Statistik zur durchschnittlichen Größe und Gewicht 
# je nach Altersgruppe. 
# 2. Geben Sie Altersgruppen mit durchschnittlichen Gewicht >= 85.1 an
df["Alter"] = pd.Timestamp("now").year - pd.to_datetime(n_df["Geburtsdatum"]).dt.year
df["Altersgruppe"] = df["Alter"].apply(lambda alter: altersgruppe(alter))


agg_df = df.groupby(["Altersgruppe"])[["Größe_cm", "Gewicht_kg" ]].mean()
agg_df[agg_df["Gewicht_kg"]>85.1]

                Größe_cm  Gewicht_kg
Altersgruppe
Erwachsen     179.994841   85.190088
Senior        179.804691   85.226063

In [ ]:
agg_df.loc["Kind"] # Zeile auswählen
agg_df.loc["Kind", "Größe_cm"] # Wert in der Zeile "Kind" und Spalte "Größe_cm"
agg_df.loc[:,"Gewicht_kg"] # Spaltenauswahl in der Matrixnotation
agg_df.loc["Erwachsen":"Kind",:] # Slicing
df.loc[:500,"Vorname":] # Alle Spalten von "Vornamen" bis Ende, die ersten 500 Zeilen
df.loc[:,:"Raucher"] # alle Spalten bis "Raucher"
df.loc[100:200,"Hausarzt":"Familienstand"] # Zeile 100 bis Zeile 200, Spalte "Hausarzt" bis Spalte "Familienstand"

,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand
100,Franz-Josef Trommler,168,114,True,Nüsse,2025-05-08,20.4,verheiratet
101,Josip Schleich,205,125,False,keine,2025-01-19,23.7,verheiratet
102,Jane Karge,156,122,True,keine,2025-02-28,25.6,verwitwet
103,Sylwia Ritter,204,123,False,Nüsse,2025-05-20,22.9,verheiratet
104,Kathi Jähn,144,76,True,Pollen,2025-03-11,33.5,verwitwet
...,...,...,...,...,...,...,...,...
196,Anne-Katrin Gorlitz,175,122,True,Nüsse,2025-05-14,29.1,verheiratet
197,Dietrich Siering,147,70,True,keine,2025-03-15,31.0,ledig
198,Katy Dietz,142,107,True,Gluten,2025-03-17,32.2,ledig
199,Vitus Kohl,148,114,False,Nüsse,2025-04-20,31.6,verwitwet
200,Irmela Hellwig,141,122,False,Pollen,2025-07-29,21.0,geschieden

In [90]:
# komplexere Auswahl

df.loc[[5,10],["Allergien","Größe_cm"]].loc[df["Alter"]>25]

   Allergien  Größe_cm
10    Gluten       157

In [ ]:
df.loc[5,"Größe_cm"]
df.at[5,"Größe_cm"] # empfohlen bei Zugriff auf Einzelwerte
df.loc[5,"Größe_cm"] = 166  # Zuweisung
df.at[5,"Größe_cm"]

np.int64(166)

In [94]:
agg_df

                Größe_cm  Gewicht_kg
Altersgruppe
Erwachsen     179.994841   85.190088
Kind          179.901982   85.098743
Senior        179.804691   85.226063

In [105]:
agg_df.iloc[1] # Zeile auswählen
agg_df.iloc[1, 0] # Wert in der Zeile "Kind" und Spalte "Größe_cm"
agg_df.iloc[:,1] # Spaltenauswahl in der Matrixnotation
agg_df.iloc[0:2,:] # Slicing
df.iloc[:500,2:] # Alle Spalten von "Vornamen" bis Ende, die ersten 500 Zeilen
df.iloc[:,:15] # alle Spalten bis "Raucher"
df.iloc[100:200,11:19] # Zeile 100 bis Zeile 200, Spalte "Hausarzt" bis Spalte "Familienstand"

,Hausarzt,Größe_cm,Gewicht_kg,Raucher,Allergien,Letzes_EKG,BMI,Familienstand
100,Franz-Josef Trommler,168,114,True,Nüsse,2025-05-08,20.4,verheiratet
101,Josip Schleich,205,125,False,keine,2025-01-19,23.7,verheiratet
102,Jane Karge,156,122,True,keine,2025-02-28,25.6,verwitwet
103,Sylwia Ritter,204,123,False,Nüsse,2025-05-20,22.9,verheiratet
104,Kathi Jähn,144,76,True,Pollen,2025-03-11,33.5,verwitwet
...,...,...,...,...,...,...,...,...
195,Axel Werner,179,108,True,Milch,2025-06-21,28.1,verheiratet
196,Anne-Katrin Gorlitz,175,122,True,Nüsse,2025-05-14,29.1,verheiratet
197,Dietrich Siering,147,70,True,keine,2025-03-15,31.0,ledig
198,Katy Dietz,142,107,True,Gluten,2025-03-17,32.2,ledig
199,Vitus Kohl,148,114,False,Nüsse,2025-04-20,31.6,verwitwet

In [ ]:
df.to_pickle("patient.pk") # Pickle = binäres Serialisierungsformat
# Verwenden Sie nicht, wenn Sie nicht wissen wer und wie die Pickle-Datei
# erstellt worden ist.